menu:
    Blog: /
    About: /about/
    Archive: /archives/
    GitHub: https://github.com/rlcode
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: rlcode
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-65209371-5

# Copyright Infomation
startyear: 2017
